### PR TITLE
Fixed window property

### PR DESCRIPTION
**Pull request by siamak**

### CODE REVIEW

**Comment by ShinyChang** [comment]
@siamak 
`this` works fine in browser and Node. Any reason for this change?

**Comment by siamak** [comment]
in ES6, in this case:
```javascript
const modal = () => {
    $templates.append(tmpl('glossary', data));
}
```
`this` in case is `undefined` but `window` is working.

**Comment by blueimp** [comment]
You seem to have superfluous control characters in your commit, which break the StandardJS linting tests.

Could you also provide a failing test case?
The code example you provide doesn't seem to be the source of your issue as far as I understand it.

**Comment by ionurboz** [comment]
[****](onur)

**Comment by vinyll** [comment]
I assume this could be closed, right?

**Comment by blueimp** [comment]
@vinyll yes, thanks.

**Pull request closed without merging**
